// Generated by scripts/generate-car-manifest.mjs — do not edit by hand.
// Run `npm run generate:cars` after adding photos (also runs automatically
// before `npm run dev` / `npm run build`). See public/cars/README.md for
// the naming convention.
import carPhotos from "./car-photos.generated.json";

export type CarAngle = "front" | "three-quarter" | "side" | "rear";

const ALL_ANGLES: CarAngle[] = ["front", "three-quarter", "side", "rear"];

export type PorscheModel = {
  id: string;
  name: string;
  /** Which angles have an image available for this model */
  angles: CarAngle[];
};

// Modern (2015+, pre-electric-transition) Porsche model lines, split by
// body style where the roofline is a real silhouette difference (911
// Carrera/Cabriolet/Targa, 718 Cayman/Boxster) — never by trim or engine
// badge alone (S, T, GT, 4, Turbo, etc).
export const MODELS: PorscheModel[] = [
  { id: "911-carrera", name: "911 Carrera", angles: ALL_ANGLES },
  { id: "911-cabriolet", name: "911 Cabriolet", angles: ALL_ANGLES },
  { id: "911-targa", name: "911 Targa", angles: ALL_ANGLES },
  { id: "718-cayman", name: "718 Cayman", angles: ALL_ANGLES },
  { id: "718-boxster", name: "718 Boxster", angles: ALL_ANGLES },
  { id: "panamera", name: "Panamera", angles: ALL_ANGLES },
  { id: "macan", name: "Macan", angles: ALL_ANGLES },
  { id: "cayenne", name: "Cayenne", angles: ALL_ANGLES },
  { id: "taycan", name: "Taycan", angles: ALL_ANGLES },
  { id: "918-spyder", name: "918 Spyder", angles: ALL_ANGLES },
];

export type ImageCredit = {
  photographer: string;
  source: string;
  license: string;
};

// Attribution for real (non-placeholder) photos sourced from Wikimedia
// Commons or similar, keyed by "<modelId>/<filename>" (the exact file in
// public/cars/<modelId>/). Only photos listed here get a credit line in
// the UI — the original 3 launch photos (panamera/side.jpg,
// taycan/three-quarter.jpg, 718-cayman/three-quarter.jpg) predate this
// system, are AI-generated rather than real photos, and are intentionally
// left uncredited.
export const IMAGE_CREDITS: Record<string, ImageCredit> = {
  "911-carrera/front.jpg": {
    photographer: "Alexandre Prevot",
    source: "https://commons.wikimedia.org/wiki/File:Gray_Porsche_992_Carrera.jpg",
    license: "CC BY-SA 4.0",
  },
  "911-carrera/three-quarter.jpg": {
    photographer: "Alexander Migl",
    source: "https://commons.wikimedia.org/wiki/File:Porsche_992.2_coupes_IMG_4597.jpg",
    license: "CC BY-SA 4.0",
  },
  "911-carrera/side.jpg": {
    photographer: "Alexandre Prevot",
    source: "https://commons.wikimedia.org/wiki/File:Porsche_992_Carrera_(2).jpg",
    license: "CC BY-SA 4.0",
  },
  "911-carrera/rear.jpg": {
    photographer: "TTTNIS",
    source: "https://commons.wikimedia.org/wiki/File:2025_Porsche_911_Carrera_S_rear.jpg",
    license: "CC0 1.0",
  },
  "911-cabriolet/front.jpg": {
    photographer: "Vauxford",
    source:
      "https://commons.wikimedia.org/wiki/File:2020_Porsche_911_Carrera_S_Automatic_Convertible_3.0_Front.jpg",
    license: "CC BY-SA 4.0",
  },
  "911-cabriolet/three-quarter.jpg": {
    photographer: "Calreyn88",
    source: "https://commons.wikimedia.org/wiki/File:2024_Porsche_911_992_Carrera_S.jpg",
    license: "CC BY-SA 4.0",
  },
  "911-cabriolet/side.jpg": {
    photographer: "KarleHorn",
    source: "https://commons.wikimedia.org/wiki/File:P992_Cabrio_geschlossen.JPG",
    license: "CC BY-SA 4.0",
  },
  "911-cabriolet/rear.jpg": {
    photographer: "Vauxford",
    source:
      "https://commons.wikimedia.org/wiki/File:2020_Porsche_911_Carrera_S_Automatic_Convertible_3.0_Rear.jpg",
    license: "CC BY-SA 4.0",
  },
  "911-targa/front.jpg": {
    photographer: "先従隗始",
    source: "https://commons.wikimedia.org/wiki/File:Porsche_3BA-992NA2_911_Targa_4_(24010611193).jpg",
    license: "CC0 1.0",
  },
  "911-targa/three-quarter.jpg": {
    photographer: "Hugh Llewelyn",
    source: "https://commons.wikimedia.org/wiki/File:2023_Porsche_911_Targa.jpg",
    license: "CC BY-SA 4.0",
  },
  "911-targa/side.jpg": {
    photographer: "Calreyn88",
    source: "https://commons.wikimedia.org/wiki/File:2022_Porsche_911_Targa_4S_(27185).jpg",
    license: "CC BY-SA 4.0",
  },
  "911-targa/rear.jpg": {
    photographer: "先従隗始",
    source: "https://commons.wikimedia.org/wiki/File:Porsche_3BA-992NA2_911_Targa_4_(24010611185).jpg",
    license: "CC0 1.0",
  },
  "718-boxster/front.jpg": {
    photographer: "HJUdall",
    source: "https://commons.wikimedia.org/wiki/File:17_Porsche_718_Boxster_Base.jpg",
    license: "CC0 1.0",
  },
  "718-boxster/three-quarter.jpg": {
    photographer: "MercurySable99",
    source: "https://commons.wikimedia.org/wiki/File:2018_Porsche_718_Boxster,_front_right,_08-17-2023.jpg",
    license: "CC BY-SA 4.0",
  },
  "718-boxster/side.jpg": {
    photographer: "Iain Cameron",
    source: "https://commons.wikimedia.org/wiki/File:At_Culduie_hamlet_-_Applecross_(1)_(47532539762).jpg",
    license: "CC BY 2.0",
  },
  "718-boxster/rear.jpg": {
    photographer: "Iain Cameron",
    source: "https://commons.wikimedia.org/wiki/File:At_Clachaig_Inn,_Glencoe_(1)_(47532541162).jpg",
    license: "CC BY 2.0",
  },
  "718-cayman/front.jpg": {
    photographer: "Calreyn88",
    source: "https://commons.wikimedia.org/wiki/File:2020_Porsche_718_Cayman_GT4_(23096).jpg",
    license: "CC BY-SA 4.0",
  },
  "718-cayman/side.jpg": {
    photographer: "Calreyn88",
    source: "https://commons.wikimedia.org/wiki/File:2016_Porsche_718_Cayman_GTS.jpg",
    license: "CC BY-SA 4.0",
  },
  "718-cayman/rear.jpg": {
    photographer: "Calreyn88",
    source: "https://commons.wikimedia.org/wiki/File:2018_Porsche_718_Cayman_2.jpg",
    license: "CC BY-SA 4.0",
  },
  "macan/front.jpg": {
    photographer: "メイド理世",
    source: "https://commons.wikimedia.org/wiki/File:Porsche_Macan_(front)_24_September_2024.jpg",
    license: "CC BY-SA 4.0",
  },
  "macan/three-quarter.jpg": {
    photographer: "Aos.1905",
    source:
      "https://commons.wikimedia.org/wiki/File:Porsche_Macan_(2020)_(front_three-quarter_view)_in_Osaka.jpg",
    license: "CC BY-SA 4.0",
  },
  "macan/side.jpg": {
    photographer: "Saschaporsche",
    source: "https://commons.wikimedia.org/wiki/File:Porsche_Macan_-_right_side.JPG",
    license: "CC BY-SA 3.0",
  },
  "macan/rear.jpg": {
    photographer: "メイド理世",
    source: "https://commons.wikimedia.org/wiki/File:Porsche_Macan_(rear)_24_September_2024.jpg",
    license: "CC BY-SA 4.0",
  },
  "cayenne/front.jpg": {
    photographer: "茅野ふたば",
    source: "https://commons.wikimedia.org/wiki/File:Porsche_Cayenne_Macau_front_view_(July_14,_2025).jpg",
    license: "CC BY-SA 4.0",
  },
  "cayenne/three-quarter.jpg": {
    photographer: "HJUdall",
    source: "https://commons.wikimedia.org/wiki/File:23_Porsche_Cayenne_Base.jpg",
    license: "CC0 1.0",
  },
  "cayenne/side.jpg": {
    photographer: "Grandmaster Huon",
    source: "https://commons.wikimedia.org/wiki/File:Grey_porsche_cayenne_12_40_37_493000.jpeg",
    license: "CC BY-SA 4.0",
  },
  "cayenne/rear.jpg": {
    photographer: "茅野ふたば",
    source: "https://commons.wikimedia.org/wiki/File:Porsche_Cayenne_Macau_rear_view_(July_14,_2025).jpg",
    license: "CC BY-SA 4.0",
  },
  "918-spyder/front.jpg": {
    photographer: "Ethan Llamas",
    source: "https://commons.wikimedia.org/wiki/File:2015_Porsche_918_Spyder,_front_right,_06-08-2024.jpg",
    license: "CC BY-SA 4.0",
  },
  "918-spyder/three-quarter.jpg": {
    photographer: "Ethan Llamas",
    source: "https://commons.wikimedia.org/wiki/File:2015_Porsche_918_Spyder,_front_left,_06-08-2024.jpg",
    license: "CC BY-SA 4.0",
  },
  "918-spyder/side.jpg": {
    photographer: "Benoit cars",
    source: "https://commons.wikimedia.org/wiki/File:918_side_(14374138534).jpg",
    license: "CC BY-SA 2.0",
  },
  "918-spyder/rear.jpg": {
    photographer: "Ethan Llamas",
    source: "https://commons.wikimedia.org/wiki/File:2015_Porsche_918_Spyder,_rear_right,_06-08-2024.jpg",
    license: "CC BY-SA 4.0",
  },
  "panamera/front.jpg": {
    photographer: "Retired electrician",
    source: "https://commons.wikimedia.org/wiki/File:Moscow,_Porsche_Panamera_Aug_2025_03.jpg",
    license: "CC0 1.0",
  },
  "panamera/three-quarter.jpg": {
    photographer: "OWS Photography",
    source: "https://commons.wikimedia.org/wiki/File:Porsche_Panamera_(971)_Washington_DC_Metro_Area,_USA.jpg",
    license: "CC BY 4.0",
  },
  "panamera/rear.jpg": {
    photographer: "Retired electrician",
    source: "https://commons.wikimedia.org/wiki/File:Moscow,_Porsche_Panamera_Aug_2025_01.jpg",
    license: "CC0 1.0",
  },
  "taycan/front.jpg": {
    photographer: "OWS Photography",
    source: "https://commons.wikimedia.org/wiki/File:Porsche_Taycan_Washington_DC_Metro_Area,_USA.jpg",
    license: "CC BY 4.0",
  },
  "taycan/side.jpg": {
    photographer: "HJUdall",
    source: "https://commons.wikimedia.org/wiki/File:22_Porsche_Taycan_Base.jpg",
    license: "CC0 1.0",
  },
  "taycan/rear.jpg": {
    photographer: "Ethan Llamas",
    source: "https://commons.wikimedia.org/wiki/File:Porsche_Taycan_Dolomite_Silver_Metallic_02.jpg",
    license: "CC BY-SA 4.0",
  },
};

const PHOTO_MANIFEST = carPhotos as Record<string, Record<CarAngle, string[]>>;

export type ResolvedCarImage = {
  path: string;
  credit: ImageCredit | undefined;
};

/**
 * Picks a photo for a model + angle. When multiple photos exist for that
 * angle (see public/cars/README.md), one is chosen at random each time this
 * is called. Falls back to a placeholder SVG if no real photo exists yet.
 */
export function resolveCarImage(modelId: string, angle: CarAngle): ResolvedCarImage {
  const photos = PHOTO_MANIFEST[modelId]?.[angle] ?? [];
  if (photos.length > 0) {
    const filename = photos[Math.floor(Math.random() * photos.length)];
    return {
      path: `/cars/${modelId}/${filename}`,
      credit: IMAGE_CREDITS[`${modelId}/${filename}`],
    };
  }
  return { path: `/cars/${modelId}/${angle}.svg`, credit: undefined };
}

export type Question = {
  answer: PorscheModel;
  options: PorscheModel[];
  correctIndex: number;
};

function shuffle<T>(arr: T[]): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

// One round per model line — no repeats.
export function buildQuiz(count = MODELS.length): Question[] {
  const order = shuffle(MODELS).slice(0, count);
  return order.map((answer) => {
    const distractors = shuffle(MODELS.filter((m) => m.id !== answer.id)).slice(0, 3);
    const options = shuffle([answer, ...distractors]);
    return {
      answer,
      options,
      correctIndex: options.findIndex((o) => o.id === answer.id),
    };
  });
}
